name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install
          run: npm install
        - name: Install Allure
          run: npm install -g allure-commandline --save-dev
        - name: Test
          env:
            username: ${{ secrets.BS_USER }}
            access-key: ${{ secrets.BS_KEY }}
          run: npx wdio config/wdio.android.bs.conf.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
        - name: Archive Test results
          uses: actions/upload-artifact@v3
          with:
            name: allure-results
            path: allure-results
        - name: Archive Test report
          uses: actions/upload-artifact@v3
          with:
            name: allure-report
            path: allure-report
